language: node_js
node_js:
- '8'
deploy:
  skip_cleanup: true
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: asEQK4zyD920zRn35kWE0FIVVRrIDMTLqTXPn5VqcqFJOFYM/d2XDOfw9jB6C3X/YSDBDF82JBujMmteVpa/ZslGoH9G7G/AzH0rRTiwmiiF4FP+S05tN7SwZbkT873WQHxKMqQbYkcU33BLguMuUDhrTFS4mbCR69Yrv7tYt2/rVt7af4iNOqD5rCsJnFStZers4P6o7koiwRaAgmN/0//Zrb694VW+V0ZbTTsyCApaPqQWFxx2LgaP/FeqUwCtWGtLnkAU4GFtptBuds/ICED6gKaBtPKBr8Izfp/GRi6E5KSdyPOLKIopInfnpTMNy9x1XE5WLvDjGM4Xtrw1TCiKfBqR/QsdOlPb25e2lxsD1xxJ+VfinRNHM0WxvsDKXYxc96O9MAILQATLmXzAvftQMlroZIs0izBti96Fcvx5GDCFfHdFZaKbwYL1AvyrFm4fZPB0c0tvB/fJc4+G1Fc6FB/MNhKISNoVQ6gsFZrbeJ+WqjZY28WqvlRwkQsBL/R8KmDe7DtymtyuCoKNJhBmY+0e4oDPakTGGqSgD7EZ2/qsIFKcvQ/0ogon5k2ZNfWYc3dkeiok9i2zJ2rCi4k9Aci1ZU2xOf4fZFXlgY5g1RUtrPNg9soJ5mqZhsljOYAhXsS3djTIdg/oap1gjf3fKgN97vQ3MwoZ8QndjIc=
  on:
    tags: true
    repo: LuvDaSun/promise-u
